# Generated by Django 5.1.3 on 2024-11-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('full_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
    ]
