# Generated by Django 5.1.3 on 2024-11-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='social/')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('imagine', models.CharField(max_length=100)),
            ],
        ),
    ]
