# Generated by Django 5.1.3 on 2024-11-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=150)),
                ('location_url', models.URLField()),
            ],
        ),
    ]
