# Generated by Django 5.1.3 on 2024-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('B', 'Beginner'), ('E', 'Elementary'), ('I', 'Intermediate'), ('A', 'Advanced'), ('N', 'Native')], max_length=2)),
                ('image', models.ImageField(upload_to='language/')),
            ],
        ),
    ]
