# Generated by Django 5.1.3 on 2024-11-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='degree',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], max_length=20),
        ),
    ]
