# Generated by Django 5.1.3 on 2024-11-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='academy',
        ),
    ]
